# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\"O\n\nAudioChunk\x12\x13\n\x0b\x61udio_array\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x05\"<\n\x13TranscriptionResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\x32V\n\x14TranscriptionService\x12>\n\x13StreamTranscription\x12\x0b.AudioChunk\x1a\x14.TranscriptionResult\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=23
  _globals['_AUDIOCHUNK']._serialized_end=102
  _globals['_TRANSCRIPTIONRESULT']._serialized_start=104
  _globals['_TRANSCRIPTIONRESULT']._serialized_end=164
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=166
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
