# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\rtranscription\",\n\x11TranscriptRequest\x12\x17\n\x0f\x61udio_file_path\x18\x01 \x01(\t\"(\n\x12TranscriptResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t2t\n\x14TranscriptionService\x12\\\n\x11StreamTranscripts\x12 .transcription.TranscriptRequest\x1a!.transcription.TranscriptResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIPTREQUEST']._serialized_start=38
  _globals['_TRANSCRIPTREQUEST']._serialized_end=82
  _globals['_TRANSCRIPTRESPONSE']._serialized_start=84
  _globals['_TRANSCRIPTRESPONSE']._serialized_end=124
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=126
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
